import type { Metadata } from 'next'
import '@/app/globals.scss'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ConfigProvider, App } from 'antd'
import theme from '@/theme/themeConfig'
import '@ant-design/v5-patch-for-react-19'

export const metadata: Metadata = {
  title: 'Quản lý sinh viên',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <App>{children}</App>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
